### ISSUE TITLE
Inline snapshot testing

### ISSUE THREAD

**Issue by msrose** [syrupy-project/syrupy#122]
Opening an issue for discussion purposes, no defined requirements or suggestions for how (or whether) this should be implemented):

See https://jestjs.io/docs/en/snapshot-testing#inline-snapshots for how jest handles inline snapshots.

It would be cool if syrupy could support something this since it's really nice for certain cases.

**Comment by iamogbz** [comment]
Ignoring the complications of modifying the source code for automatic snapshot insertion, what would the syntax look like?

```py
assert actual_data == snapshot(inline="")
```

Where the presence of the `inline` key prevents the snapshot from being written to file and the failure diff shows what needs to be copied into the inline string.

```py
assert actual_data == snapshot(inline="""
  dict({
    'list': list([
      2,
    ]),
    'nested': dict({
      'other': 'value',
    }),
  })
""")
```

Or maybe it can a snapshot extension instead?

**Comment by 15r10nk** [comment]
hi, I'm the author of [inline-snapshot](https://github.com/15r10nk/inline-snapshot) and I found this issue while I was reading through your issues to find inspiration for my own library.

Maybe inline-snapshot provides some inspiration for you, because putting the values into the source code is its the main function.

sneak peek:

``` python
from inline_snapshot import snapshot

data = dict(
    {
        "list": list([2]),
        "nested": dict({"other": "value"}),
    }
)


def test_data():
    assert data == snapshot({"list": [2], "nested": {"other": "value"}})
```

**Comment by noahnu** [comment]
@15r10nk I'd be happy to link out to your project in our README for folks looking for inline snapshots. I think adding inline snapshots to syrupy would introduce unnecessary complexity to this project (and bloat the size of the library quite a bit).

**Comment by 15r10nk** [comment]
Thank you very much @noahnu
