### ISSUE TITLE
How to implement image diffing for visual regression testing

### ISSUE THREAD

**Issue by noahnu** [syrupy-project/syrupy#566]
### Discussed in https://github.com/tophat/syrupy/discussions/536

<div type='discussions-op-text'>

<sup>Originally posted by **rassie** August  4, 2021</sup>
If I understand the documentation correctly, it's possible to implement a snapshot extension which would compare images visually (e.g. with [pixelmatch](https://pypi.org/project/pixelmatch/)) instead of byte-wise. Is it a matter of writing a custom `SnapshotReporter` and mix it into an extension or would I need to do more? </div>

**Comment by drjasonharrison** [comment]
What is the status of being able to create a custom SnapshotReporter that uses a tool like pixelmatch?

**Comment by noahnu** [comment]
It should be doable now. Something along the lines of:

```py
class PixelMatchSnapshotExtension(PNGImageSnapshotExtension):
    def matches(self, *, serialized_data, snapshot_data) -> bool:
        pass # run pixelmatch here

    def diff_snapshots(self, serialized_data, snapshot_data) -> "SerializableData":
        pass # re-run pixelmatch and return a diff image (can cache on the class instance)

@pytest.fixture
def visual_snapshot(snapshot):
    return snapshot.use_extension(PixelMatchSnapshotExtension)

def test_case(visual_snapshot):
    assert generate_image(....) == visual_snapshot
```

matches: https://github.com/tophat/syrupy/blob/b831ee21b54f0b0dd287a7a0c6e138d6b553f26b/src/syrupy/extensions/base.py#L404

**Comment by noahnu** [comment]
This should be doable using a custom extension, see above comment. Closing the issue.
