### ISSUE TITLE
Store snapshot assertion index in snapshot file 

### ISSUE THREAD

**Issue by noahnu** [syrupy-project/syrupy#569]
We had to wrap custom names in square brackets because our "does assertion name match name in file" logic is brittle. See: https://github.com/tophat/syrupy/pull/563 and related PR.

**Comment by iamogbz** [comment]
Damn this was missed in the v2 release, could probably have merged both number and string indexes to use the same pattern e.g `# name: TestClass.test_class_method_name[1]`

**Comment by iamogbz** [comment]
Maybe a larger change (since it's gonna be breaking) would be to split the index from the name in the snapshot header e.g.
```py
# ---
# name: TestClass.test_class_method_name[parameterized1]
# index: 1
```

**Comment by iamogbz** [comment]
Hey 👋🏾 trying to figure how this can work with the current state of things, would it require a new snapshot file version, how does it work with `TaintedSnapshotError`? Catching up on the code base, but comments would be appreciated.

Also don't see any more tasks queued in [project/up next](https://github.com/orgs/tophat/projects/6), so prioritising the oldest/easiest issues.

**Comment by noahnu** [comment]
I'll try find some time towards the end of this week to do some general project maintenance (comments + prioritized backlog).

Will give a longer answer when at my computer but in general yes, we'd need a new serializer version. A new serializer version will automatically leverage the tainted snapshot error to force snapshots to be considered "invalid" and require updates. This is necessary because adding additional metadata around a snapshot, e.g. index, does not actually cause a snapshot inequality/failed match. So as long as you change the version, you don't have to worry about the taint error (it's automatic).

If you're interested, I think the old issue around supporting extremely large snapshots would be a good one to pick up.

**Comment by noahnu** [comment]
We'd have to update a number of methods to support splitting out the index from the name. E.g. in "delete_snapshotS" we don't pass in the index, we pass in a set of snapshot names to delete.

Going to close out this issue as won't fix since I think it's low priority and I'm unlikely to get to it -- though happy to re-open if someone wants to pick it up or it's blocking some workflow.
