### ISSUE TITLE
Add option to disable snapshot diffing

### ISSUE THREAD

**Issue by RobertCraigie** [syrupy-project/syrupy#581]
**Is your feature request related to a problem? Please describe.**

I have multiple massive (~10k lines) snapshots and if any of them fail it takes a considerable amount of time to produce the diff. I also don't need to know what the difference is in this case.

An example snapshot can be found here: https://github.com/RobertCraigie/prisma-client-py/blob/main/tests/test_generation/exhaustive/__snapshots__/test_exhaustive/test_async%5Bactions.py%5D.raw

**Describe the solution you'd like**

Add a new config / cli option to disable diff creation and instead just show an error that the snapshots differ.

**Describe alternatives you've considered**

None that I can think of.

**Additional context**

This was discovered from this CI run: https://github.com/RobertCraigie/prisma-client-py/runs/4859619412?check_suite_focus=true which I cancelled after 14 minutes (it usually takes at most 3 minutes to complete).

**Comment by noahnu** [comment]
Interesting. At first I thought this was a duplicate of https://github.com/tophat/syrupy/issues/577, but your case has short line length, just a larger number of lines.

An option to disable the diff makes sense to me though I also wonder if we can achieve a diff in a reasonable amount of time. Or have some heuristic to fallback to a different diff format/system for large snapshots.

**Comment by RobertCraigie** [comment]
> I also wonder if we can achieve a diff in a reasonable amount of time.

I think that would be an incredible feat! I let another workflow run its course and it took 1 hour and 30 minutes to produce 4 snapshot diffs: https://github.com/RobertCraigie/prisma-client-py/runs/4886243053?check_suite_focus=true

**Comment by BasitAli** [comment]
Have a similar problem, I have pytest-timeout and the tests are timing out while preparing the diff. This may be similar to #625 in a way, but at the moment, I'm also looking for just a way to disable diff if the snapshot doesn't match.

**Comment by BasitAli** [comment]
Temporary resolved it using a custom snapshot extension,

```python
class NoDiffSnapshotExtension(SingleFileSnapshotExtension):
    def diff_snapshots(self, serialized_data, snapshot_data):
        return "diff-is-disabled"

    def diff_lines(self, serialized_data, snapshot_data):
        return ["diff", "is", "disabled"]
```

**Comment by noahnu** [comment]
This will land in syrupy 4.8.0 -- I'm batching up a few other bug fixes/minor features in the release.

To disabling diffing, just set `--snapshot-diff-mode=disabled`. The default mode is what I'm calling "detailed". Left it open ended so we can add a few other out of the box options like byte-length comparisons or other diff algorithms.
