### ISSUE TITLE
SyntaxError: invalid syntax on pytest --snapshot-update

### ISSUE THREAD

**Issue by alexjolig** [syrupy-project/syrupy#844]
I just installed syrupy and tried `pytest --snapshot-update` to produce the snapshots. at the first test including the snapshot fixture, I have this line:
`base_url = "some-url"`
and I get this error:

```
E       pytest --snapshot-update    base_url = "some-url"
E                                   ^
E   SyntaxError: invalid syntax
```

How to reproduce?

Add this test:

```
def test_get_current_user(get_headers, snapshot):
    base_url = "some-url"
    response = requests.get(
        f"https://{base_url}/api/account_manager/user/me",
        headers={**get_headers, "Content-Type": "application/json"},
    )
    result = response.json()
    assert response.status_code == 200
    assert result == snapshot
```

run:
`pytest  --snapshot-update`

**Environment:**

- OS: Ubuntu
- Syrupy Version: 4.6.0
- Python Version: 3.9

**Comment by noahnu** [comment]
I don't think this is related to syrupy. This looks like you probably have a mismatched whitespace causing a syntax error.
