### ISSUE TITLE
Ignoring parameters when comparing snapshot to serialized object

### ISSUE THREAD

**Issue by irahorecka** [syrupy-project/syrupy#861]
**How to ignore parameters when comparing snapshot to serialized object?**

My collaborators and I naturally run tests on different machines, therefore, classes / functions that have file path parameters will have different values when taking snapshots. How do I deliberately ignore this parameter (e.g., `filename`) altogether? I would like one centralized snapshot that can be compared without the comparison of file paths, if possible.

I've tried using `snapshot(exclude=props("filename"))` (`filename` is the parameter to ignore) to no avail.

![Screen Shot 2024-03-11 at 2 12 18 PM](https://github.com/tophat/syrupy/assets/48743671/4897581c-ec0c-416d-a6ac-28fe77bb0b91)

**Comment by yedpodtrzitko** [comment]
it looks like `filename` is not a property in the root of the snapshot, which is why it's ignored. You have to specify the path to the property.

Or, instead of excluding the property, you can use [matcher](https://tophat.github.io/syrupy/#matcher) to check just the value type instead of checking the actual value:



```
snapshot(
    matcher=path_type({
        "path.to.filename.property": (str,), # the value is expected to be `str`
    })
)
```

**Comment by noahnu** [comment]
If you decide to use a matcher as @yedpodtrzitko mentions, you have the option of using regex for the path. This would let you match on any filename property, no matter how nested.

See: https://github.com/syrupy-project/syrupy?tab=readme-ov-file#path_typemappingnone--types-stricttrue-regexfalse
