### ISSUE TITLE
Loosen python version requirement from `>=3.8.1,<4` to `>=3.8.1`

### ISSUE THREAD

**Issue by Ravencentric** [syrupy-project/syrupy#866]
**Is your feature request related to a problem? Please describe.**

Libraries that may want to use syrupy cannot do so if they declare their python version without a ceiling version.

For example, assume my library declares the following dependency:
```toml
[tool.poetry.dependencies]
python = ">=3.9"
```
Syrupy is compatible with the above, but a poetry install will fail:
```
❯ poetry add syrupy -G dev
Using version ^4.6.1 for syrupy

Updating dependencies
Resolving dependencies... (0.3s)

The current project's supported Python range (>=3.9) is not compatible with some of the required packages Python requirement:
  - syrupy requires Python >=3.8.1,<4, so it will not be satisfied for Python >=4

Because no versions of syrupy match >4.6.1,<5.0.0
 and syrupy (4.6.1) requires Python >=3.8.1,<4, syrupy is forbidden.
So, because pyanilist depends on syrupy (^4.6.1), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For syrupy, a possible solution would be to set the `python` property to ">=3.9,<4"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Describe the solution you'd like**
Loosen python version requirement from `>=3.8.1,<4` to `>=3.8.1`

**Describe alternatives you've considered**
Force users to add the `<4` python version marker

**Additional context**
N/A

**Comment by noahnu** [comment]
Considering python releases breaking changes between minor version updates, if I was being pedantic, I'd lower the ceiling to the max version we test against. I'm on board with relaxing this version :+1:
